name: mxbase
key: zero
publish_to: 'none'
description: A new flutter plugin project.
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.2
  event_bus: ^2.0.0
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  velocity_x: ^3.6.0
  flutter_staggered_grid_view: ^0.4.0
  carousel_slider: ^4.0.0
  flutter_screenutil:
    git: https://gitee.com/sevenskid_admin/fp_screen.git
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.8
  chat_bubbles:
    git: https://gitee.com/sevenskid_admin/fp_chatbubble.git
  go_router: ^4.5.1
  image: ^4.0.15
  gxz_dropdown_menu:
    git: https://gitee.com/sevenskid_admin/dropdown_menu.git
  flutter_file_downloader:
    git: https://gitee.com/sevenskid_admin/fp_downloader.git
  webview_flutter:
    git: https://gitee.com/sevenskid_admin/fn_web.git
  flutter_swipe_action_cell: ^2.1.1
  photo_view: ^0.12.0
  flutter_native_player:
    git: https://gitee.com/sevenskid_admin/fn_player.git
  flutter_svg: ^1.1.4
  flutter_riverpod: ^2.3.0
  tap_debouncer: ^2.0.0
  logger: ^1.1.0
  intl: ^0.17.0
  clipboard: ^0.1.3
  flutter_custom_tab_bar: ^1.2.1
  jiffy: ^4.1.0
  crypto: ^3.0.1
  xrandom: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.leaf.fli.mxbase
        pluginClass: MxbasePlugin
      ios:
        pluginClass: MxbasePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
